services:
  booru-api:
    container_name: booru-api
    build:
      context: .
    volumes:
      - .:/app/booru-api
    restart: unless-stopped
    ports:
      - "${PORT:-6600}:${PORT:-6600}"
    env_file:
      - .env
    networks:
      - booru-network

networks:
  booru-network:
    driver: bridge
